name: Update Scholar Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 给予写内容的权限

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 使用Python 3.9或更高版本
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run dynamic stats update
        run: |
          python get_stats.py
        continue-on-error: true  # 即使脚本失败也继续工作流程
      
      - name: Create fallback badges if needed
        run: |
          # 检查徽章文件是否存在，如果不存在则创建
          if [ ! -f badge-citations.json ]; then
            echo '{
              "schemaVersion": 1,
              "label": "citations",
              "message": "N/A",
              "color": "gray",
              "style": "flat-square"
            }' > badge-citations.json
          fi
          
          if [ ! -f badge-hindex.json ]; then
            echo '{
              "schemaVersion": 1,
              "label": "h-index",
              "message": "N/A",
              "color": "gray",
              "style": "flat-square"
            }' > badge-hindex.json
          fi
          
          if [ ! -f badge-i10index.json ]; then
            echo '{
              "schemaVersion": 1,
              "label": "i10-index",
              "message": "N/A",
              "color": "gray",
              "style": "flat-square"
            }' > badge-i10index.json
          fi
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scholar stats" && git push)