name: Update Scholar Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 给予写内容的权限

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      
      - name: Create test badge data
        run: |
          # 创建简单的静态JSON文件，确保徽章可以显示
          echo '{
            "schemaVersion": 1,
            "label": "citations",
            "message": "123",
            "color": "blue"
          }' > badge-citations.json
          
          echo '{
            "schemaVersion": 1,
            "label": "h-index",
            "message": "5",
            "color": "green"
          }' > badge-i10index.json
          
          echo '{
            "schemaVersion": 1,
            "label": "i10-index",
            "message": "3",
            "color": "orange"
          }' > badge-i10index.json
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update scholar stats" && git push)